### ISSUE TITLE
Bug: CSS Styles

### ISSUE THREAD

**Issue by James-Kua** [pilcrowOnPaper/malta#8]
Image is overflowing the width of the page

<img width="794" alt="image" src="https://github.com/pilcrowOnPaper/malta/assets/61898455/271ce5b4-2c51-4ca7-b2d9-83b62cdeea92">

Suggested fix:
```
img {
    max-width: 100%;
    height: auto;
    object-fit: cover;
}
```

After: 
<img width="764" alt="image" src="https://github.com/pilcrowOnPaper/malta/assets/61898455/7065f2c1-718a-4573-8aac-ad90937c8ff9">

---
List elements that are bolded have a new line

<img width="750" alt="image" src="https://github.com/pilcrowOnPaper/malta/assets/61898455/01f94684-665c-4c7e-98ec-a8885dfc7b91">

Suggested fix: remove the line below
https://github.com/pilcrowOnPaper/malta/blob/c561d9f8424ed9041d1ab4d24c5e20ec8c9e9ed9/src/commands/build/assets/markdown.css#L54

After:

<img width="766" alt="image" src="https://github.com/pilcrowOnPaper/malta/assets/61898455/2cd294ca-e07d-4160-a4bd-f65329a8cdeb">

**Comment by pilcrowOnPaper** [comment]
I don't think the list one is a styling issue
<img width="449" alt="Screenshot 2024-03-10 at 15 59 35" src="https://github.com/pilcrowOnPaper/malta/assets/80624252/7928d28a-4ebc-4748-bda1-396cd50b9184">

**Comment by James-Kua** [comment]
I think I see why,  you are using 

```
- `--port` (`-p`): Localhost port (number - `3000` by default)`
```

But I am using 
```
+ **Automated deployment and updates**: Kubernetes provides a declarative...
```

If it is deemed to be wrong usage, I can remove the list styling fix from the PR

**Comment by pilcrowOnPaper** [comment]
I mean like I edited the html to be

```html
<b>port<b>
```

**Comment by James-Kua** [comment]
Okay, reverted the list styling fix, please have a look
